### ISSUE TITLE
Upload Service Operation "Mailbox Submission" returns "Unknown Operation: mailbox"

### ISSUE THREAD

**Issue by SiHeMa** [grahamegrieve/fhirserver#10]
Posting a Message Bundle to http://fhir-dev.healthintersections.com.au/open/#upload

returns

<?xml version="1.0" encoding="UTF-8"?>
<OperationOutcome xmlns="http://hl7.org/fhir">
  <text>
    <status value="generated"/>
    <div xmlns="http://www.w3.org/1999/xhtml">
      <p>Unknown Operation: mailbox</p>
    </div>
  </text>
  <issue>
    <severity value="error"/>
    <details value="Unknown Operation: mailbox"/>
  </issue>
</OperationOutcome>

**Comment by grahamegrieve** [comment]
remove all support for mailbox from DSTU2+ server
