### ISSUE TITLE
Issues with searching

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#11]
take this valueset: http://fhir-dev.healthintersections.com.au/open/ValueSet/107

it should be returned in this query:
    http://fhir-dev.healthintersections.com.au/open/ValueSet?name=Conn
but isn’t...

This one works: http://fhir-dev.healthintersections.com.au/open/ValueSet?name=LOINC

This doesn’t work either…

 http://fhir-dev.healthintersections.com.au/open/ValueSet?name=Connectathon

**Comment by grahamegrieve** [comment]
This is a string searching issue. For discussion but fixed for now
