### ISSUE TITLE
Issue with expansion

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#12]
This query: http://fhir-dev.healthintersections.com.au/open/ValueSet/valueset-observation-codes/$expand?filter=pulse

results in this response:

<OperationOutcome 
    xmlns="http://hl7.org/fhir">
    <text>
        <status value="generated"/>
        <div 
            xmlns="http://www.w3.org/1999/xhtml">
            <p>not a cardinal list</p>
        </div>
    </text>
    <issue>
        <severity value="error"/>
        <details value="not a cardinal list"/>
    </issue>
</OperationOutcome>

**Comment by grahamegrieve** [comment]
Fixed. Cache/version management
