### ISSUE TITLE
Duplicate case value in fsl_utils.pas 

### ISSUE THREAD

**Issue by dkounal** [grahamegrieve/fhirserver#120]
Using Delphi 10.4.2 to compile the FHIR Server in Windows64 I get the E2030 Duplicate case value in line 16668
Moving that first I noticed that the    ` #$F1 : result := 'n';` has the same label with     `#$03C1 : result := 'p';`
I can not explain it

**Comment by grahamegrieve** [comment]
line 16668 of what unit?

**Comment by dkounal** [comment]
fhirserver\library\fsl\fsl_utilities.pas

**Comment by grahamegrieve** [comment]
I don't understand. #$F1 is not the same as #$03C1

**Comment by dkounal** [comment]
neither do I
![duplicate label](https://user-images.githubusercontent.com/37013295/122688590-dab74980-d225-11eb-81b2-390b80519ea3.png)

**Comment by dkounal** [comment]
Trying to compile it in Win32 I can getting also:
[dcc32 Fatal Error] IdSSLOpenSSLHeaders.pas(192): F1026 File not found: 'IdCompilerDefines.inc'

**Comment by dkounal** [comment]
Also, I change it to: 
`    #$00F1 : result := 'n';`
and now it is happy and no duplicate labels found

**Comment by grahamegrieve** [comment]
Should be fixed then
