### ISSUE TITLE
Query bundle sometimes incomplete

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#13]
This resource: http://fhir-dev.healthintersections.com.au/open/StructureDefinition/clinfhirtest5

has a name of 'test5' and so should be in this query:

The response bundle has a 'total' value of 1, but there are no resources included.

**Comment by sillyhound25** [comment]
here's another example: http://fhir-dev.healthintersections.com.au/open/Condition/13
and a query: http://fhir-dev.healthintersections.com.au/open/Condition?patient=206

**Comment by grahamegrieve** [comment]
Can't reproduce
