### ISSUE TITLE
delete not working

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#21]
try: DELETE http://fhir-dev.healthintersections.com.au/open/Valueset/dhay

you get 

{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p>Access violation at address 0000000000EFC25C in module 'FHIRServer.exe'. Read of address 0000000000000068</p></div>"
    },
    "issue": [
        {
            "severity": "error",
            "details": "Access violation at address 0000000000EFC25C in module 'FHIRServer.exe'. Read of address 0000000000000068"
        }
    ]
}

**Comment by grahamegrieve** [comment]
has been fixed
