### ISSUE TITLE
Rejecting Condition resource that looks OK

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#22]
Error "Unrecognized Content Code" at evidence...

{
  "resourceType": "Condition",
  "meta": {
    "lastUpdated": "2015-08-26T18:15:56+12:00"
  },
  "text": {
    "status": "generated",
    "div": "<div><div>code:Asthma finding (finding)</div><div>verificationStatus:confirmed</div><div>encounter:period:From2015-08-03 to 2015-08-05status:arrived</div><div>code:ASAs</div><div>code:asas</div></div>"
  },
  "code": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "390798007",
        "display": "Asthma finding (finding)"
      }
    ],
    "text": "Asthma finding (finding)"
  },
  "verificationStatus": "confirmed",
  "encounter": {
    "reference": "Encounter/1",
    "display": "2015-08-03 -> 2015-08-05"
  },
  "evidence": [
    {
      "code": {
        "text": "ASAs"
      }
    },
    {
      "code": {
        "text": "asas"
      }
    }
  ],
  "patient": {
    "reference": "Patient/2",
    "display": "Adam Everyman "
  }
}

**Comment by grahamegrieve** [comment]
fixed now (after fixing the narrative)
