### ISSUE TITLE
Not validating StructureDefinition

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#23]
Try this:

GET /StructureDefinition/Basic
remove the id from the resource
POST /StructureDefinition

error: (sample)

"issue": [
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/tools#issue-source",
                    "valueCode": "InstanceValidator"
                }
            ],
            "severity": "error",
            "code": "structure",
            "diagnostics": "Unrecognised Content telecom",
            "location": [
                "/f:StructureDefinition/f:contact[0]"
            ]
        },
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/tools#issue-source",
                    "valueCode": "InstanceValidator"
                }
            ],
            "severity": "error",
            "code": "structure",
            "diagnostics": "Unrecognised Content telecom",
            "location": [
                "/f:StructureDefinition/f:contact"
            ]
        },
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/tools#issue-source",
                    "valueCode": "InstanceValidator"
                }
            ],
            "severity": "error",
            "code": "structure",
            "diagnostics": "Unrecognised Content identity",
            "location": [
                "/f:StructureDefinition/f:mapping[0]"
            ]
        },
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/tools#issue-source",
                    "valueCode": "InstanceValidator"
                }
            ],
            "severity": "error",
            "code": "structure",
            "diagnostics": "Unrecognised Content uri",
            "location": [
                "/f:StructureDefinition/f:mapping[0]"
            ]
        },
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/tools#issue-source",
                    "valueCode": "InstanceValidator"
                }
            ],
            "severity": "error",
            "code": "structure",
            "diagnostics": "Unrecognised Content name",
            "location": [
                "/f:StructureDefinition/f:mapping[0]"
            ]
        },
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/tools#issue-source",
                    "valueCode": "InstanceValidator"
                }
            ],
            "severity": "error",
            "code": "structure",
            "diagnostics": "Unrecognised Content identity",
            "location": [
                "/f:StructureDefinition/f:mapping"
            ]
        },
        {
            "extension": [
...

**Comment by grahamegrieve** [comment]
Works now
