### ISSUE TITLE
Valid (I think) MedicationOrder rejected

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#24]
The following resource was rejected:

{
        "resourceType": "MedicationOrder",
        "meta": {
          "lastUpdated": "2015-08-27T15:49:29+12:00"
        },
        "text": {
          "status": "generated",
          "div": "<div><div>text:1 tab twice a day</div></div>"
        },
        "medicationReference": {
          "reference": "Medication/1",
          "display": "Medication"
        },
        "dosageInstruction": [
          {
            "text": "1 tab twice a day"
          }
        ],
        "patient": {
          "reference": "Patient/2",
          "display": "Adam Everyman "
        }
      }

with an issue:

"issue": [
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/tools#issue-source",
                    "valueCode": "InstanceValidator"
                }
            ],
            "severity": "error",
            "code": "structure",
            "diagnostics": "Unrecognised Content text",
            "location": [
                "/f:MedicationOrder/f:dosageInstruction"
            ]
        }
    ]

**Comment by grahamegrieve** [comment]
The text is not valid
