### ISSUE TITLE
Valid (I think) Conformance rejected

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#25]
{
    "kind": "requirements",
    "description": "The functionality of a Terminology server required by clinFhir",
    "resourceType": "Conformance",
    "date": "2015-09-01",
    "fhirVersion": "1.0.0",
    "acceptUnknown": "both",
    "format": ["json"],
    "rest": [{
        "mode": "client",
        "resource": [{
            "type": "ValueSet",
            "interaction": [
                {"code": "read"},
                {"code": "create"},
                {"code": "update"}
            ],
            "searchParam": [{
                "name": "url",
                "type": "uri"
            }]
        }]
    }]

}

**Comment by grahamegrieve** [comment]
This has been fixed
