### ISSUE TITLE
notepad++ plugin - bundle validation ends up with a schematron violation

### ISSUE THREAD

**Issue by wdebeau1** [grahamegrieve/fhirserver#30]
Validating the attached file results in a schematron violation of bdl-7 FullUrl must be unique in a bundle, or else entries with the same fullUrl must have different meta.versionId).

However, the fullUrls are unique. The bundle passes a validate when posted to the server (though the bundle also passes a validate when posted to the server if the fullUrls are the same; not sure why?)

[testbundle.txt](https://github.com/grahamegrieve/fhirserver/files/43117/testbundle.txt)

**Comment by grahamegrieve** [comment]
fixed in release 1.0.7+
