### ISSUE TITLE
notepad++ plugin - Validating a transaction Bundle gives errors for resources with no id

### ISSUE THREAD

**Issue by wdebeau1** [grahamegrieve/fhirserver#31]
When validating a transaction bundle with resources that are going to be created, the validator raises errors such as
error Bundle.entry.item(0).resource.Patient (@ line 6/ col 10) Resource has no id  invalid 

However, resources being created shouldn't have ids (or at least that's what the bundle-transaction example says).

Attached bundle can be used to replicate the issue.

**Comment by wdebeau1** [comment]
[testbundle.txt](https://github.com/grahamegrieve/fhirserver/files/47370/testbundle.txt)

**Comment by grahamegrieve** [comment]
fixed per discussion on implementers channel
