### ISSUE TITLE
notepad++ plugin - editing partially complete resources throws continual errors

### ISSUE THREAD

**Issue by wdebeau1** [grahamegrieve/fhirserver#33]
If there's an xml file open containing, say, an Appointment, and it starts out valid
attempt to add a new tag, and after I hit <, a dialog box pops up saying "The text associated with this error code could not be found". Click ok, type a character, the dialog comes back up. This continues until the resource is at least well-formed.

Though when I just tried this and added an element named s with no value, I got an access violation from fhirnpp.dll.

It seems like something is continually parsing the document, but I haven't been able to find anything in the FHIR plugin that indicates that it might be doing this.

**Comment by grahamegrieve** [comment]
Oops. debugging notification released accidentally.
