### ISSUE TITLE
notepad++ plugin - validation error occurring on timing when it shouldn't

### ISSUE THREAD

**Issue by wdebeau1** [grahamegrieve/fhirserver#36]
When validating MedicationOrders (for example, medicationorderexample8(medrx008).xml from the example zip
<periodUnits value="d"/>
results in
The value provided is not in the value set http://hl7.org/fhir/ValueSet/units-of-time (http://hl7.org/fhir/ValueSet/units-of-time, and a code is required from this value set

However, d is a code in that valueset.

**Comment by grahamegrieve** [comment]
Fixed as of server release 1.0.5 (server side bug)
