### ISSUE TITLE
Compiling on Delphi XE7

### ISSUE THREAD

**Issue by johnkbird** [grahamegrieve/fhirserver#4]
1 - IndySoap – we are using XE7, and the IdCompilerDefines.inc in the source folder only goes as far as XE3 – on copying one of the standard XE7 IdCompilerDefines.inc from the Indy files under program files Embarcadero helped.  In case it helps I have attached the Xe7 and XE3 files so you can check these, the IdCompilerDefines.inc is the XE7 Indy version.

We are compiling for XE7, this introduces some compiler alterations in generics it seems:

2 - In unit AdvGenerics.pas

function TAdvEnumerable<T>.ToArrayImpl(Count: Integer): TArray<T>;
var
  x: T;
begin
  // We assume our caller has passed correct Count
  SetLength(Result, Count);
  Count := 0;
  for x in Self do
  begin
    TObject(Result[Count]) := TAdvObject(x).Link;     //####JKB – have to cast the result to TObject in XE7
    Inc(Count);
  end;
end;

procedure TAdvList<T>.InsertRange(Index: Integer; const Values: array of T);
var
  I: Integer;
begin
  if (Index < 0) or (Index > Count) then
    raise EArgumentOutOfRangeException.CreateRes(@SArgumentOutOfRange);

  GrowCheck(Count + Length(Values));
  if Index <> Count then
  begin
    FArrayManager.Move(FItems, Index, Index + Length(Values), Count - Index);
    FArrayManager.Finalize(FItems, Index, Length(Values));
  end;

  for I := 0 to Length(Values) - 1 do
    TObject(FItems[Index + I]) := TAdvObject(Values[I]).Link; // yes, here we link. This means that the user cannot construct an array of objects and link them assuming this will respect that
            //####JKB have to cast the result to TObject in XE7

  Inc(FCount, Length(Values));

  for I := 0 to Length(Values) - 1 do
    Notify(Values[I], cnAdded);
end;

0.	TADVObject – Enumerator

3 - 

FHIRSUpport.pas
procedure TFHIRRequest.LoadParams(form: TIdSoapMimeMessage);
[dcc32 Error] FHIRSupport.pas(798): E2003 Undeclared identifier: 'ParamName'

We suspect that this may be meant to be ID instead of ParamName, but it makes us suspect that there is a later version of IndySoap than we have been able to get from the net.  

The Indy Soap version we have used was V2  R22 from

http://sourceforge.net/p/indysoap/code-0/22/tree/trunk/

4 – Likely also not having the latest version of Indy Soap

procedure TFhirOperationManager.ExecuteQuestionnaireGeneration(request: TFHIRRequest; response : TFHIRResponse);
var
  profile : TFHIRProfile;
  op : TFhirOperationOutcome;
  resourceKey : integer;
  originalId, id, fid : String;
  builder : TQuestionnaireBuilder;
  questionnaire : TFHIRQuestionnaire;
begin
  try
    NotFound(request, response);
    if check(response, opAllowed(request.ResourceType, request.CommandType), 400, lang, StringFormat(GetFhirMessage('MSG_OP_NOT_ALLOWED', lang), [CODES_TFHIRCommandType[request.CommandType], CODES_TFHIRResourceType[request.ResourceType]])) then
    begin
      if (request.id = '') or ((length(request.id) <= ID_LENGTH) and FindResource(frtProfile, request.Id, false, resourceKey, originalId, request, response, request.compartments)) then
      begin
        profile := nil;
        try
          // first, we have to identify the value set.
          id := request.Id;
          if request.Id <> '' then // and it must exist, because of the check above
            profile := GetProfileById(request, request.Id, request.baseUrl)
          else if request.Parameters.VarExists('identifier') then
            profile := GetProfileByURL(request.Parameters.getvar('identifier'), id)
          else if (request.form <> nil) and request.form.hasParam('profile') then           //####JKB  hasParam  undefined
            profile := LoadFromFormParam(request.form.getparam('profile'), request.Lang) as TFhirProfile      //####JKB getParam undefined
          else if (request.Resource <> nil) and (request.Resource is TFhirProfile) then
            profile := request.Resource.Link as TFhirProfile
          else
            raise Exception.Create('Unable to find profile to convert (not provided by id, identifier, or directly');

          if id <> '' then
          begin
            fid := request.baseUrl+'Profile/'+id+'/$questionnaire';
            questionnaire := FRepository.QuestionnaireCache.getQuestionnaire(frtProfile, id);
          end
          else
          begin
            fid := newGUIDUrn;
            questionnaire := nil;
          end;

          try
            if questionnaire = nil then
            begin
              builder := TQuestionnaireBuilder.Create;
              try
                builder.Profile := profile.link;
                builder.OnExpand := FRepository.ExpandVS;
                builder.onLookupCode := FRepository.LookupCode;
                builder.Context := request.Link;
                builder.onLookupReference := LookupReference;
                builder.QuestionnaireId := fid;
                builder.build;
                questionnaire := builder.questionnaire.Link;
                if id <> '' then
                  FRepository.QuestionnaireCache.putQuestionnaire(frtProfile, id, questionnaire, builder.dependencies);
              finally
                builder.Free;
              end;
            end;
            response.HTTPCode := 200;
            response.Message := 'OK';
            response.Body := '';
            response.LastModifiedDate := now;
            response.ContentLocation := ''; // does not exist as returned
            response.Resource := questionnaire.Link;
          finally
            questionnaire.Free;
          end;
        finally
          profile.free;
        end;
        op := FRepository.validator.validateInstance(nil, response.Resource, 'Produce Questionnaire', nil);
        try
          if (op.hasErrors) then
          begin
            response.HTTPCode := 500;
            response.Message := 'Questionnaire Generation Failed';
            response.Resource.xmlId := 'src';
            op.containedList.Add(response.Resource.Link);
            response.Resource := op.link;
          end;
        finally
          op.Free;
        end;
      end;
    end;
    inc(iCount);
    TFHIRXhtmlComposer.Create('en').Compose(TFileStream.Create('c:\temp\q'+inttostr(iCount)+'.xml', fmCreate), response.Resource, true, nil);
    AuditRest(request.session, request.ip, request.ResourceType, request.id, response.versionId, request.CommandType, request.Provenance, request.OperationName, response.httpCode, '', response.message);
  except
    on e: exception do
    begin
      AuditRest(request.session, request.ip, request.ResourceType, request.id, response.versionId, request.CommandType, request.Provenance, request.OperationName, 500, '', e.message);
      raise;
    end;
  end;
end;
{$ENDIF}

The errors from the compiler are
[dcc32 Error] FHIROperation.pas(4200): E2003 Undeclared identifier: 'hasParam'
[dcc32 Error] FHIROperation.pas(4200): E2015 Operator not applicable to this operand type
[dcc32 Error] FHIROperation.pas(4201): E2003 Undeclared identifier: 'getparam'
[dcc32 Error] FHIROperation.pas(5504): E2003 Undeclared identifier: 'hasParam'
[dcc32 Error] FHIROperation.pas(5504): E2015 Operator not applicable to this operand type
[dcc32 Error] FHIROperation.pas(5505): E2003 Undeclared identifier: 'getparam'
[dcc32 Error] FHIROperation.pas(5682): E2003 Undeclared identifier: 'hasParam'
[dcc32 Error] FHIROperation.pas(5682): E2003 Undeclared identifier: 'hasParam'
[dcc32 Error] FHIROperation.pas(5683): E2015 Operator not applicable to this operand type
[dcc32 Error] FHIROperation.pas(5683): E2015 Operator not applicable to this operand type
[dcc32 Error] FHIROperation.pas(5687): E2015 Operator not applicable to this operand type
[dcc32 Error] FHIROperation.pas(5732): E2003 Undeclared identifier: 'hasParam'
[dcc32 Error] FHIROperation.pas(5732): E2015 Operator not applicable to this operand type
[dcc32 Error] FHIROperation.pas(5733): E2003 Undeclared identifier: 'getparam'
[dcc32 Error] FHIROperation.pas(5742): E2003 Undeclared identifier: 'hasParam'
[dcc32 Error] FHIROperation.pas(5742): E2015 Operator not applicable to this operand type
[dcc32 Error] FHIROperation.pas(5745): E2003 Undeclared identifier: 'getParam'
[dcc32 Error] FHIROperation.pas(5747): E2003 Undeclared identifier: 'hasParam'
[dcc32 Error] FHIROperation.pas(5747): E2015 Operator not applicable to this operand type
[dcc32 Error] FHIROperation.pas(5748): E2003 Undeclared identifier: 'getParam'
[dcc32 Fatal Error] FHIRSubscriptionManager.pas(136): F2063 Could not compile used unit 'FHIROperation.pas'

5 - One of the other programmers here (Donald Hillier) is also having some issues with the JSON parser:

The inbuilt JSON parser in XE7 conflicts with the namespace of the Grieve parser – we have renamed your parser to ggjson to get around this (ie json functions with the same function names and incompatible parameters etc).  We can give more detail about this if it helps.

**Comment by grahamegrieve** [comment]
I think I have fixed all these
