### ISSUE TITLE
UCUM valueset not expanding

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#40]
The following URL results in an empty expansion node

http://fhir2.healthintersections.com.au/open/ValueSet/uslab-units/$expand

**Comment by grahamegrieve** [comment]
I have no idea how to expand this value set...

**Comment by grahamegrieve** [comment]
this an expansion on a code system that's got no fixed enumeration (it's a grammar). You cannot expand the full code system. But if you explicitly say that you're happy for an incomplete expansion (using an expansion profile in DSTU2.1+, or the parameter _incomplete=true in DSTU2), then my server (from 1.0.13) will return the UCUM common units.
