### ISSUE TITLE
Notepad++ Appointment Participant Type Error

### ISSUE THREAD

**Issue by mcoolidge** [grahamegrieve/fhirserver#42]
None of the codes provided are in the value set http://hl7.org/fhir/ValueSet/c80-practice-codes 

"coding": [
                  {
                    "system": "http://www.hl7.org/fhir/v3/ParticipationType/index.html",
                    "code": "ATND",
                    "display": "attender"
                  }
                ]

**Comment by grahamegrieve** [comment]
the system is wrong - it should be 'http://hl7.org/fhir/v3/ParticipationType' - so this is working correctly.
