### ISSUE TITLE
notepad app opening blank web pages instead of displaying narrative??

### ISSUE THREAD

**Issue by Healthedata1** [grahamegrieve/fhirserver#46]

**Comment by grahamegrieve** [comment]
This was transient - it should be fixed in build 11

**Comment by Healthedata1** [comment]
still generating blank browser windows.  and not generating narrative errors: access violation at address 0000000000040960D in module 'FHIRServer.exe'. read of address...

**Comment by grahamegrieve** [comment]
fixed now
