### ISSUE TITLE
ValueSet Expansion filtering

### ISSUE THREAD

**Issue by brianpos** [grahamegrieve/fhirserver#5]
When performing a valueset expansion, exclude the definition sections of the results, and just return the expansion section.
(specifically excluding the define and compose sections)

**Comment by grahamegrieve** [comment]
it's not wrong, by the definition, to leave the definition details in the value set - and sometimes, it what would be wanted. So I can't simply drop them. at best, it would have to be a flag - the definition of the operation expects that to be in the profile flag. So I can define a profile for this. Let's say, the profile value http://www.healthintersections.com.au/fhir/expansion/no-details

**Comment by grahamegrieve** [comment]
Done.
