### ISSUE TITLE
UCUM fails to load in version 1.0.30

### ISSUE THREAD

**Issue by mjosborne1** [grahamegrieve/fhirserver#50]
I got 1.0.30 to install OK, but when I execute FHIRServer.exe -debug (or -start) I get the attached bug. This is the DEBUG trace. Could be something to do with loading the UCUM XML file from the cache?? There is no ucum.cache file in the package but the is a ucum-essense.xml file. Is this a problem?

[ErrorRunningFHIRServer_1_0_30.txt](https://github.com/grahamegrieve/fhirserver/files/110982/ErrorRunningFHIRServer_1_0_30.txt)
![programdatafiles_20160131](https://cloud.githubusercontent.com/assets/693010/12698223/e7d29992-c7e2-11e5-9fbc-f569b19d6d68.PNG)

**Comment by mjosborne1** [comment]
This is the relevant part of fhirserver.ini:

[snomed]
; where to load snomed from. see program instructions for how to import snomed
cache=

[loinc]
; where to load loinc from. see program instructions for how to import loinc
cache=C:\ProgramData\FHIRServer\loinc.cache

[rxnorm]
; which database to find and import rxnorm into
database=

[ucum]
; where to load ucum from. The file name for ucum-essence.xml from unitsofmeasure.org
source=
cache=C:\ProgramData\FHIRServer\ucum-essence.xml

**Comment by mjosborne1** [comment]
Just as a test, I downloaded the ucum essence file from the source http://unitsofmeasure.org/ucum-essence.xml . I put it in the ProgramData folder, but it fails to load in the same way as the included xml file.

**Comment by grahamegrieve** [comment]
it's an installer issue - it sets ucum cache = not ucum source=

I've fixed it in the next release

Grahame


On Sun, Jan 31, 2016 at 11:56 AM, Michael Osborne <notifications@github.com>
wrote:

> Just as a test, I downloaded the ucum essence file from the source
> http://unitsofmeasure.org/ucum-essence.xml . I put it in the ProgramData
> folder, but it fails to load in the same way as the included xml file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grahamegrieve/fhirserver/issues/50#issuecomment-177350448>
> .
>



-- 
-----
http://www.healthintersections.com.au / grahame@healthintersections.com.au
/ +61 411 867 065

**Comment by mjosborne1** [comment]
OK, Thanks!

On 31 January 2016 at 20:03, Grahame Grieve <notifications@github.com>
wrote:

> it's an installer issue - it sets ucum cache = not ucum source=
>
> I've fixed it in the next release
>
> Grahame
>
>
> On Sun, Jan 31, 2016 at 11:56 AM, Michael Osborne <
> notifications@github.com>
> wrote:
>
> > Just as a test, I downloaded the ucum essence file from the source
> > http://unitsofmeasure.org/ucum-essence.xml . I put it in the ProgramData
> > folder, but it fails to load in the same way as the included xml file.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/grahamegrieve/fhirserver/issues/50#issuecomment-177350448
> >
> > .
> >
>
>
>
> --
> -----
> http://www.healthintersections.com.au / grahame@healthintersections.com.au
> / +61 411 867 065
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grahamegrieve/fhirserver/issues/50#issuecomment-177453403>
> .
>



-- 
Michael Osborne

**Comment by mjosborne1** [comment]
This has fixed my problem, I am now on 1.0.31 Thanks!

Could I please ask that the following line in bold be added to _post-install.txt_ for people who have already installed an older version (this would have saved me some time)?


(1) edit fhirserver.ini 
  - configure database access 
  - configure the web address settings and ports and certificates
  - create a GUID and set the SCIM salt 
  - Define an admin user in the ini file [adminuser] section
  - generally review other settings
(2) possibly edit auth.ini to configure oauth relationships etc
(3) initialise the database: run fhirserver.exe -mount -password yourpassword

**if this is an upgrade from an older version of fhirserver: run fhirserver.exe -remount -password yourpassword**

**Comment by grahamegrieve** [comment]
done

Grahame


On Tue, Feb 2, 2016 at 8:29 PM, Michael Osborne <notifications@github.com>
wrote:

> This has fixed my problem, I am now on 1.0.31 Thanks!
>
> Could I please ask that the following line in bold be added to
> *post-install.txt* for people who have already installed an older version
> (this would have saved me some time)?
>
> (1) edit fhirserver.ini
>
>    - configure database access
>    - configure the web address settings and ports and certificates
>    - create a GUID and set the SCIM salt
>    - Define an admin user in the ini file [adminuser] section
>    - generally review other settings (2) possibly edit auth.ini to
>    configure oauth relationships etc (3) initialise the database: run
>    fhirserver.exe -mount -password yourpassword
>
> *if this is an upgrade from an older version of fhirserver: run
> fhirserver.exe -remount -password yourpassword*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grahamegrieve/fhirserver/issues/50#issuecomment-178473888>
> .
>



-- 
-----
http://www.healthintersections.com.au / grahame@healthintersections.com.au
/ +61 411 867 065

**Comment by mjosborne1** [comment]
Ta

On 2 February 2016 at 21:06, Grahame Grieve <notifications@github.com>
wrote:

> done
>
> Grahame
>
>
> On Tue, Feb 2, 2016 at 8:29 PM, Michael Osborne <notifications@github.com>
> wrote:
>
> > This has fixed my problem, I am now on 1.0.31 Thanks!
> >
> > Could I please ask that the following line in bold be added to
> > *post-install.txt* for people who have already installed an older version
> > (this would have saved me some time)?
> >
> > (1) edit fhirserver.ini
> >
> > - configure database access
> > - configure the web address settings and ports and certificates
> > - create a GUID and set the SCIM salt
> > - Define an admin user in the ini file [adminuser] section
> > - generally review other settings (2) possibly edit auth.ini to
> > configure oauth relationships etc (3) initialise the database: run
> > fhirserver.exe -mount -password yourpassword
> >
> > *if this is an upgrade from an older version of fhirserver: run
> > fhirserver.exe -remount -password yourpassword*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/grahamegrieve/fhirserver/issues/50#issuecomment-178473888
> >
>
> > .
> >
>
>
>
> --
> -----
> http://www.healthintersections.com.au / grahame@healthintersections.com.au
> / +61 411 867 065
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grahamegrieve/fhirserver/issues/50#issuecomment-178511969>
> .
>



-- 
Michael Osborne
