### ISSUE TITLE
Valueset expansion munging loinc codes

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#6]
Try the following URL:

http://fhir-dev.healthintersections.com.au/openValueSet/valueset-observation-codes/$expand?filter=temp

The expansion looks like this:

  <contains>
            <system value="http://loinc.org"/>
            <code value="3&#x00;5&#x00;0&#x00;9&#x00;5&#x00;-&#x00;9"/>
            <display value="Body temperature panel"/>
        </contains>

or in JSON:

{
                "system": "http://loinc.org",
                "code": "2\u00000\u00000\u00009\u00003\u0000-\u00001",
                "display": "Temperature Humidifier"
            },

SNOMED seems OK...

**Comment by grahamegrieve** [comment]
Oops. fixed (upgrade soon)
