### ISSUE TITLE
Resource with extension being rejected

### ISSUE THREAD

**Issue by sillyhound25** [grahamegrieve/fhirserver#7]
the following resource is being rejected by a POST to http://fhir-dev.healthintersections.com.au/open/Patient:

 {
  "resourceType": "Patient",
  "meta": {
    "lastUpdated": "2015-04-20T15:35:37+12:00",
    "profile": [
      "http://hl7.org/fhir/StructureDefinition/cda-patient-role"
    ]
  },
  "text": {
    "status": "generated",
    "div": "<div><div>extension:Adventist</div></div>"
  },
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/us-core-religion",
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/v3/ReligiousAffiliation",
            "code": "1001",
            "display": "Adventist"
          }
        ],
        "text": "Adventist"
      }
    }
  ]
}
error is: "details": "Required attribute 'url' is missing.\r\n",
            "location": [
                "line 13, Col 13"
            ]
looks OK to me…

**Comment by grahamegrieve** [comment]
fixed. upgrade soon.
