### ISSUE TITLE
DSTU 2 (version 0.50) FHIR-Specification -- corrupted Zip file

### ISSUE THREAD

**Issue by pete-welch** [grahamegrieve/fhirserver#8]
Grahame,

Get the following error when unzipping the 0.50 spec:

Windows cannot open the folder. The compressed folder '...fhir-spec.zip' is invalid.

7zip partly extracts then hangs about midway. Other unzip programs crash like 7Zip.

I see your reference to building our own spec but looks a bit daunting.

Some folks on the Fhir chat log complain of the same problem but nobody has offered a solution. Not sure who is in charge of the download zips.

Thank you,

Pete

**Comment by grahamegrieve** [comment]
this is fixed now, I believe
