### ISSUE TITLE
CapabilityStatement tool - save as XML saves as JSON

### ISSUE THREAD

**Issue by JohnMoehrke** [grahamegrieve/fhirserver#84]
Using 0.0.11 version of the CapabilityStatement tool. When I create a capability statement and save. The default type to save is XML, so I save as XML.. but looking at the resulting file shows that it is actually JSON. If I change the default type to JSON, it does indeed save as JSON.

**Comment by grahamegrieve** [comment]
fixed with release 0.0.3
