### ISSUE TITLE
normalized tables DDL to support FHIR in RDBMS

### ISSUE THREAD

**Issue by boristyukin** [grahamegrieve/fhirserver#86]
Hi @grahamegrieve, have you worked by any chance or felt the need to normalize FHIR documents into RDBMS flat tables? We want to load data from FHIR server for analytics and while we can store JSON documents, it is not easy to consume this data for analytics / dashboards. I wonder if you have done any work in that direction or if it even makes sense for you for that use case. I cannot find any related projects. E.g. patient resource will turn into multiple related tables with columns and simple values such as patient, patient_names, patient_identifiers etc.

**Comment by grahamegrieve** [comment]
Also raised at https://chat.fhir.org/#narrow/stream/analytics.20on.20FHIR/subject/traditional.20relational.20model. Closed - see further discussion there.
