### ISSUE TITLE
Bundle rejected on /Bundle endpoint, accepted when sent to base

### ISSUE THREAD

**Issue by mbaltus** [grahamegrieve/fhirserver#9]
When posting an example document bundle (see http://hl7-fhir.github.io/document-example-dischargesummary.html) to http://fhir-dev.healthintersections.com.au/open/Bundle, the bundle is rejected with lots of errors.
Posting the same bundle to http://fhir-dev.healthintersections.com.au/open/ results in a 202 Accepted, which is not one of the listed responses for a POST.
I had expected to see errors on both posts or no errors at all, in stead of mixed results.

**Comment by grahamegrieve** [comment]
fixed.
