### ISSUE TITLE
Toolkit crashes after launch

### ISSUE THREAD

**Issue by G-2-Z** [grahamegrieve/fhirserver#95]
I am using the binary available at http://www.healthintersections.com.au/FhirServer/ release v0.0.46 2018-09-27.
It tells me to install the base package via package manager, but immediately after closing this message window the program exits with the following error:

![Title: Application Error.
Message: Exception ELibraryException in module FHIRToolkitR3.exe at 000000000035EC05. Count not load BN_num_bits from .](https://user-images.githubusercontent.com/4152886/48133044-ca7d1680-e295-11e8-91df-1edef9873798.png)

Same for R4

**Comment by grahamegrieve** [comment]
is this OSX or windows?

**Comment by vadi2** [comment]
Same issue on Windows 10, both R4 and R3 crash out.

**Comment by grahamegrieve** [comment]
Fixed with v0.0.48
