### ISSUE TITLE
Notepad++ PluginAdmin entry for this plugin

### ISSUE THREAD

**Issue by chcg** [grahamegrieve/fhirserver#97]
See https://github.com/notepad-plus-plus/nppPluginList. You maybe want to publish the n++ plugin via this list. A zip file is needed therefore with the plugin dll at the root.

Versioninfo of the 1.0.33 release still reports to be 1.0.0.1. Which will cause issues on distribution via PA.
Do you plan to provide also a x64 version? Seems to be not the case until now.

**Comment by grahamegrieve** [comment]
ok done. including 64bit release
